version: "3.9"

services:
  app:
    build: .
    container_name: race_ctf_app
    restart: unless-stopped

    env_file:
      - .env

    volumes:
      - ./:/app              # kod źródłowy
      - ./database.db:/app/database.db  # stan bazy (zostanie skasowany przy starcie)

    ports:
      - "8000:8000"
