version: "3.9"

services:
  app:
    build: .
    container_name: race_ctf_app
    restart: unless-stopped

    # Ładujemy sekrety bez wypychania ich do obrazu
    env_file:
      - .env

    # Trzymając bazę na wolumenie, nie stracisz flag ani użytkowników
    volumes:
      - ./:/app
      - ./database.db:/app/database.db

    ports:
      - "8000:8000"
